#!/bin/bash
# ******************************************
# Program: PHP Installation
# Developer: Robson Alviani <robsonala[at]gmail.com>
# Date: 20-11-2018
# ******************************************

RET_CODE_OK=0
RET_CODE_ERROR=1
dir="$(dirname "$0")"

if [ $(id -u) -ne 0 ]; then
    echo "$0: Run it as root";
    exit $RET_CODE_ERROR;
fi

print_help() {
    echo ""
    echo "PHP installation for Ubuntu / Debian / CentOS"
    echo ""
    echo "Usage"
    echo "    [-h] Help"
    echo "    [-l] List available PHP version to install"
    echo "    [-pv] Set PHP Version"
    echo "    [-u] Run Uninstall mode"
    exit $RET_CODE_ERROR;
}

while test -n "$1"; do
 case "$1" in
 --help|-h)
 print_help
 exit $RET_CODE_OK
 ;;
 -l)
 ls php
 exit $RET_CODE_OK
 ;;
 -pv)
 ARG_PV=$2
 shift
 ;;
 -u)
 ARG_U=true
 echo "Unistalling mode"
 ;;
 *)
 echo "Unknown Argument: $1"
 exit $RET_CODE_ERROR
 ;;
 esac
 
 shift
done

if [ -z "$ARG_PV" ]; then
    echo "Set a PHP version"
    exit $RET_CODE_ERROR
elif [ ! -d "php/$ARG_PV" ]; then
    echo "PHP Version $ARG_PV not found"
    exit $RET_CODE_ERROR
fi

echo "Using PHP version $ARG_PV"

if [ "$ARG_U" ]; then
    "$dir/php/$ARG_PV/uninstall"
else
    "$dir/php/$ARG_PV/install"
fi

echo "Finished..."

exit $RET_CODE_OK