#!/bin/bash

distro=$(lsb_release -is)
codename=$(lsb_release -cs)

case $distro in
Debian|Ubuntu)
    if [ "$codename" = "trusty" ] || [ "$codename" = "xenial" ] || [ "$codename" = "bionic" ] || [ "$codename" = "stretch" ] || [ "$codename" = "jessie" ]; then
        apt-get install -y language-pack-en-base
        LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php -y
        apt-get update -y
        #apt-get install -y php7.2-fpm php7.2-curl php7.2-dev php7.2-gd php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml
        apt-get install -y php7.2-fpm
        apt-get autoremove -y
    else
        echo "Version of $distro not supported ($version / $codename)"
    fi
    ;;
CentOS)
    echo "TODO $distro"
    ;;
*)
    echo "Not supported distro ($distro)"
    ;;
esac