#!/bin/bash

distro=$(lsb_release -is)
codename=$(lsb_release -cs)

case $distro in
Debian|Ubuntu)
    if [ "$codename" = "trusty" ] || [ "$codename" = "xenial" ] || [ "$codename" = "bionic" ] || [ "$codename" = "stretch" ] || [ "$codename" = "jessie" ]; then
        #apt-get remove -y php7.2-fpm php7.2-curl php7.2-dev php7.2-gd php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml
        apt-get remove -y php7.2-fpm
        add-apt-repository --remove ppa:ondrej/php -y
        apt-get remove -y language-pack-en-base
        apt-get autoremove -y
    else
        echo "Version of $distro not supported ($version / $codename)"
    fi
    ;;
CentOS)
    echo "TODO $distro"
    ;;
*)
    echo "Not supported distro ($distro)"
    ;;
esac